(load "deftest.lisp")
(load "chapter2")
(load "chapter3")
(load "chapter4")
(load "chapter5")
(load "chapter6")
(load "chapter7")
(load "chapter10")
(load "chapter14")
(print "Loaded.  Type (tests) to run the sequence of tests.")
