
// tdf.h
// Header file for initializing the MPX operating system
//
// tours de force: http://www.ducksarepeople.com/tdf 

#ifndef TDF_H
#define TDF_H

// Constant Defitions go here mmkayyy
#define TDF_OS_VERSION "0.0.1"

// Size of our input buffer in character length
//#define BUFFER_SIZE 255


// Functions Go Down Here
// use 'extern' before the return type
extern int shell();
//extern int clean_buffer(char*, int*);

#endif

