#Range       isa: Object with: 'min max'.
#GraphReader isa: Object with: 'line array handler commentChar'.
#Graph       isa: Object with: 'label matrix height width ox oy xrange yrange'. 
					"XXX does Graph need anymore attributes?"
#Tag         isa: Object.
#TagWidth    isa: Tag.
#TagHeight   isa: Tag.
#TagLabel    isa: Tag.
#TagBottom   isa: Tag.
#TagLeft     isa: Tag.
#TagRange    isa: Tag.
#TagError    isa: Tag.


"XXX define subclasses of Tag to handle every tag"

"XXX Note that 'Tags' should run by calling 'tag'
the right number of times"
!




