include lib.mk

# What group are you?
Group=1

# What project are you doing
Proj=2b#

# Default test to run
X=0lib.st#

# Banner for top of each test
Hi=printf "\n---| $X |-----------------------------------------\n\n"

# Default action (run test $X)
all :  
	$(MAKE) X=$X test
