!! Range class methods !
new
  "auto-initialize new Ranges"
  "XXX"
!!
! Range methods !
printOn: aStream
  "print min..max"
  "XXX"
!
init
  "min's first value is very large. max's first value is min * -1"
  "XXX"
!
add: aNumber
  "take a number, reset max and min if needed"
  "XXX"
!
min: aNumber
  "take a number, reset min if needed"
  "XXX"
!
max: aNumber
  "take a number, reset max if needed"
  "XXX"
!
scale: aNumber
  "scale a number according to where it falls in the range min..max"
  "XXX" "should return a number 0 <= n <= 1"
!!
